# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: string_processor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'string_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16string_processor.proto\x12\x0fstringprocessor\"\x1d\n\rStringRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\" \n\x0eStringResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2[\n\rStringService\x12J\n\x07Process\x12\x1e.stringprocessor.StringRequest\x1a\x1f.stringprocessor.StringResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'string_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRINGREQUEST']._serialized_start=43
  _globals['_STRINGREQUEST']._serialized_end=72
  _globals['_STRINGRESPONSE']._serialized_start=74
  _globals['_STRINGRESPONSE']._serialized_end=106
  _globals['_STRINGSERVICE']._serialized_start=108
  _globals['_STRINGSERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
