
name: CI Tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup C++ & build tools
      run: sudo apt update && sudo apt install -y build-essential cmake libgtest-dev protobuf-compiler-grpc

    - name: Compile and run C++ tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: pip install -r grpc_stub/requirements.txt pytest httpx

    - name: Run Python tests
      run: pytest grpc_stub/tests/
